_target_: models.RoutingModel
layers:
  - _target_: torch.nn.Conv2d
    in_channels: 3
    out_channels: 32
    kernel_size: 3
    stride: 1
  - _target_: torch.nn.Conv2d
    in_channels: 32
    out_channels: 64
    kernel_size: 3
    stride: 1
  - _target_: torch.nn.Conv2d
    in_channels: 64
    out_channels: 128
    kernel_size: 3
    stride: 1
  - _target_: torch.nn.AdaptiveMaxPool2d
    output_size: 1
  - _target_: torch.nn.Flatten
    start_dim: 1
backbone_output_dim: 128
layers_block_n: 5
future_paths_to_sample: 5
path_selection_strategy: 'random'
prediction_mode: 'task'