#name: routing
#n_blocks_in_layer: 5
#block_type: 'conv'
#future_paths_to_sample: 5
#path_selection_strategy: 'random'
#prediction_mode: 'class'
_target_: models.RoutingModel
layers_dims: [32, 56, 128]
n_blocks_in_layer: 5
future_paths_to_sample: 5
path_selection_strategy: 'random'
prediction_mode: 'task'
block_factory:
#    _target_: hydra.utils.get_class
  _target_: hydra.utils.get_method
  path: models.routing.factory.get_conv_block
