_target_: models.RoutingModel
pre_process_module:
  _target_: torch.nn.Conv2d
  in_channels: 3
  out_channels: 16
  kernel_size: 3
  stride: 1
  bias: No
layers:
  - _target_: torch.nn.Sequential
    _args_:
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 16
        planes: 16
        stride: 1
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 16
        planes: 16
        stride: 1
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 16
        planes: 16
        stride: 1
  - _target_: torch.nn.Sequential
    _args_:
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 16
        planes: 32
        stride: 2
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 32
        planes: 32
        stride: 2
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 32
        planes: 32
        stride: 2
  - _target_: torch.nn.Sequential
    _args_:
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 32
        planes: 64
        stride: 2
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 64
        planes: 64
        stride: 2
      - _target_: models.backbone.resnet.BasicBlock
        in_planes: 64
        planes: 64
        stride: 2
  - _target_: torch.nn.Flatten
    start_dim: 1

backbone_output_dim: 64
layers_block_n: 5
future_paths_to_sample: 5
path_selection_strategy: 'random'
prediction_mode: 'task'