_target_: methods.margin.IncrementalMargin
mem_size: 200
past_task_reg: 0.1
margin: 1
warm_up_epochs: -1
future_task_reg: 0
future_margin: 0
gamma: 1
alpha: 0
rehearsal_metric: kl
margin_type: adaptive
