core:
  project_name: 'routing-cl'
  dataset_root: ./dataset/
  results_path: ./results
  version: 1
  tags: overconfidence, neural networks, deep learning, regularization, margin loss

defaults:
  - hydra: base
  - optimizer: sgd
  - experiment: base
  - override hydra/job_logging: console
  - _self_

device: cpu
#trainer:
trainer_name: ${method_path:${method._target_}}

